### ISSUE TITLE
Authentication tools

### ISSUE THREAD

**Issue by vedro-compota** [simialbi/yii2-rest-client#1]
Hi there)
What about authentication  in `simialbi/yii2-rest-client`? Is there any ability to set auth token to auth at API server?

**Comment by simialbi** [comment]
Do you mean some kind of oauth authentication? Do you have an example? It's difficult to implement to match for "all" kinds of authentication methods, but what I can do is introduce some options to configure the client. So you'd have the possibility to always pass a token with each request.
