### ISSUE TITLE
Pluralize off

### ISSUE THREAD

**Issue by MaximilianMerkert** [simialbi/yii2-rest-client#6]
Hey,

we dont use pluralisation for Rest-Webservices.
Is it Possible for you to implement a parameter into the config, that prevents the pluralisation from happening?

Atm. i removed the part of the code in the vendor, but this should be no long-term solution.

Best regards,
Max

**Comment by simialbi** [comment]
I have not finished all the work but there is a **pre-release** where this feature is built in. It may already fullfill your needs:
https://github.com/simialbi/yii2-rest-client/releases/tag/2.0.0-alpha.1
