### ISSUE TITLE
Relations and delete don't work on alpha release

### ISSUE THREAD

**Issue by mikolajzieba** [simialbi/yii2-rest-client#7]
I've tried today to integrate your alpha release, but my tests covering yii2-rest fail. 

1. Relation fetch
```
$place = Place::find()
            ->where(['id' => 1])
            ->one();

        $this->assertNotEmpty($place);

        foreach ($place->getOptions()->all() as $option) {
            $this->assertEquals(1, $option->place_id);
        }
```
It fetches all Options from the database, without filtering for a Place. 

2. Delete
Delete doesn't work. It sends:
`DELETE /index-test.php/rest/Places`
instead of:
`DELETE /index-test.php/rest/Places/39`

It's the way how `'yii\rest\UrlRule` defines REST default methods:
https://www.yiiframework.com/doc/guide/2.0/en/rest-routing

**Comment by simialbi** [comment]
Thanks for your feedback.
I could not test the relation yet, I'm going to do this. But the part with delete I can't reproduce. I added some tests to view the URLs generated and they all pass:
https://github.com/simialbi/yii2-rest-client/blob/master/tests/UrlTest.php#L71
https://travis-ci.com/simialbi/yii2-rest-client/builds/108941484

Could you post some code? How does your model `Place` look like? Or your model `Options`?

**Comment by mikolajzieba** [comment]
You are right, my case is a little different. I checked a scenario with:
```
$place->find()->where(['id' => 1]->one();
$place->delete();
```

and it worked fine. 

My case with problem:
```
        $place = new Place(['id' => 1]);
        $place->delete();
```

**Comment by simialbi** [comment]
You can't DELETE and Record which is not saved yet. If you create your Place like this:
```php
$place = new Place(['id' => 1]);
```
then `$place->isNewRecord` will be true.

About relational queries: You were right. They did not function correctly. I released [alpha.2](https://github.com/simialbi/yii2-rest-client/releases/tag/2.0.0-alpha.2) which should solve the problem. Could you check?
