### ISSUE TITLE
Bearer Auth not work with HEAD method

### ISSUE THREAD

**Issue by kmergen** [simialbi/yii2-rest-client#9]
Hi,
I work with RestDataProvider which do a HEAD Request without authorization header.
I see the Bearer token is in request->options['Authorization]. But this gives me a 401 error.
My workarround is at the moment to set the auth header in beforeSend event.

``php
// Handle BeforeSend Event
Event::on(Client::class, Client::EVENT_BEFORE_SEND, function (RequestEvent $event) {
    $r = $event->request;
    if ($r->method === 'HEAD') {
        if(array_key_exists('Authorization', $r->options))
        $r->headers->set('Authorization', $r->options['Authorization']);
    }
});
``

**Comment by simialbi** [comment]
Could you please be a bit more precise? How exactly did you use the client?

**Comment by kmergen** [comment]
Hello,
thank you for quick response.
I use it with the DataRestProvider.
The Provider do a HEAD request to get the totalCount. And in this request I
get an 401 error.
How I say in my email before if I set a header with my Bearer token it
works.

Best regards
Klaus

Am Mo., 27. Apr. 2020 um 08:42 Uhr schrieb simialbi <
notifications@github.com>:

**Comment by simialbi** [comment]
May you provide a code example? It would be easier for me to reproduce your case.

**Comment by simialbi** [comment]
@kmergen It may be fixed with the last push and the corresponding 2.0.0-beta.2 release. Could you try and give a feedback?

**Comment by kmergen** [comment]
Hi,
i will look into it.
But I find an issue with related data.
If I try a with query I get an error message.
If I try a innerjoinWith I get back the models but without the related
data. All settings in the model are made how described on docs.
I will have a deeper look  in this issues to give more information about
the error messages.

Best regards
Klaus



Am Mo., 27. Apr. 2020 um 14:52 Uhr schrieb simialbi <
notifications@github.com>:
